<template>
  <div class="identity_verify">
    <div class="title">Verify Your Identity</div>
    <div class="content">
      <div class="proccess">
        <a-steps :current="4">
          <a-popover slot="progressDot" slot-scope="{ index, status, prefixCls }">
            <template slot="content">
              <span>Step {{ index }} Status: {{ status }}</span>
            </template>
            <span :class="`${prefixCls}-icon-dot`" />
          </a-popover>
          <a-step title="Start" />
          <a-step title="Resident" />
          <a-step title="Identity" />
          <a-step title="Photo" />
          <a-step title="Security " />
          <a-step title="Status" />
        </a-steps>
      </div>
      <div class="two_authentication">
        <div class="title">Two-Factor Authentication</div>
        <div class="step_one">
          <div class="step">
            <span class="name">STEP 1:</span>
            <span>Get an authentication app</span>
          </div>
          <div class="content">
            Download and install Google Authenticator (<span class="highlight"
              >Android · iOS</span
            >), Duo Mobile (<span class="highlight">Android · iOS</span>), or Microsoft
            Authenticator (<span class="highlight">Android · iOS</span>) for your phone or
            tablet.
          </div>
        </div>
        <div class="step_two">
          <div class="step">
            <span class="name">STEP 2:</span>
            <span>Scan this QR code</span>
          </div>
          <div class="content content_02">
            Open the authentication app, tap the "+" icon in the top right of the app, and
            scan this QR code image with your phone camera.
          </div>
          <div class="QRCode">
            <qrcode-vue :value="value" :size="size" level="H" />
          </div>
          <div class="content content_02">
            Instead of scanning the QR code, you can use your authentication app's "manual
            entry" option and enter the following key:
          </div>
          <div class="hash">
            <div class="code">an3ci56xb65o3tfsk5jqqpgf</div>
            <a href="javascript:;">
              <img src="@image/icons/copyright.svg" alt="" />
            </a>
          </div>
        </div>
        <div class="step_three">
          <div class="step">
            <span class="name">STEP 3:</span>
            <span>Enter code generated by your app</span>
          </div>
          <div class="content">
            Once the QR code is scanned, enter the 6-digit code generated by your
            authentication app.
          </div>
          <a-form :form="form" @submit="handleSubmit">
            <a-form-item has-feedback>
              <a-input
                size="large"
                placeholder="Authentication Code"
                v-decorator="[
                  'code',
                  {
                    rules: [
                      {
                        required: true,
                        message: 'Please input your Authentication Code!',
                      },
                    ],
                  },
                ]"
                type="password"
              />
            </a-form-item>
            <a-form-item class="form_submit">
              <vs-button
                class="btn_started"
                color="rgb(59,222,200)"
                @click="continueFunc"
              >
                Continue
              </vs-button>
            </a-form-item>
          </a-form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import QrcodeVue from "qrcode.vue";

export default {
  transition: {
    name: "slide-fade",
    mode: "out-in",
  },
  components: {
    QrcodeVue,
    // Qrcode,
  },
  data: () => ({
    value: "https://example.com",
    size: 150,
  }),
  beforeCreate() {
    this.form = this.$form.createForm(this, { name: "authetication" });
  },
  methods: {
    handleSubmit(e) {
      e.preventDefault();
      this.form.validateFieldsAndScroll((err, values) => {
        if (!err) {
          console.log("Received values of form: ", values);
        }
      });
    },
    continueFunc() {
      this.$emit("continue");
    },
  },
};
</script>

<style lang="scss" scoped>
@import "@asset/variables.scss";
.identity_verify {
  background: rgba(255, 255, 255, 0.93);
  border: 1px solid #e4e4e4;
  box-sizing: border-box;
  box-shadow: 1px 4px 10px rgba(0, 0, 0, 0.09);
  border-radius: 20px;
  padding: 30px;
  margin: 0 50px;
  .title {
    font-weight: bold;
    font-size: 18px;
    line-height: 24px;
    color: $green-black-01;
    margin-bottom: 25px;
  }
}
.two_authentication {
  //   background: rgba(255, 255, 255, 0.93);
  //   border: 1px solid #e4e4e4;
  //   box-sizing: border-box;
  //   box-shadow: 1px 4px 10px rgba(0, 0, 0, 0.09);
  //   border-radius: 20px;
  //   padding: 30px;
  //   margin: 0 50px;

  .title {
    font-weight: 500;
    font-size: 18px;
    line-height: 24px;
    margin-bottom: 30px;
    color: $grey-black-03;
    margin-top: 20px;
  }
  .step {
    font-weight: 500;
    font-size: 18px;
    line-height: 24px;
    margin-bottom: 15px;
    .name {
      color: $green-black-01;
      font-weight: 700;
    }
  }
  .content {
    text-align: center;
    font-weight: normal;
    font-size: 13px;
    line-height: 16px;
    width: 80%;
    margin: 0 auto;
    .highlight {
      color: $green-black-01;
      font-weight: 700;
    }
  }
  .content_02 {
    width: 80%;
  }
  .QRCode {
    margin: 20px auto;
    text-align: center;
  }
  .step_one,
  .step_two,
  .step_three {
    border: 1px solid #e0e0e0;
    box-sizing: border-box;
    border-radius: 10px;
    padding: 20px 40px;
  }
  .step_two {
    margin-top: 20px;
    .hash {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      .code {
        border: 1px solid $grey-black-03;
        box-sizing: border-box;
        border-radius: 5px;
        text-align: center;
        padding: 3.5px 25px;
        font-weight: 500;
        font-size: 14px;
        margin-right: 5px;
      }
    }
  }
  .step_three {
    margin-top: 20px;

    .btn_started {
      background: linear-gradient(90.62deg, #0b9985 -63.29%, #0b9985 100%);
      border-radius: 50px;
      font-weight: 500;
      font-size: 18px;
      line-height: 24px;
      padding: 2px 20px;
    }
    .form_submit {
      display: flex;
      justify-content: center;
      margin-top: 0px;
      margin-bottom: 0px;
    }
  }
}
</style>
